puts "Seeding site contents..."

contents = [
  # Hero section
  { key: 'hero_badge', section: 'hero', label: 'Hero Badge Text', content_type: 'text', sort_order: 0,
    value_en: 'ASJJF 5-Star Ranked Event', value_ja: 'ASJJF 5つ星認定大会', value_ko: 'ASJJF 5성급 공인 대회',
    value_tl: 'ASJJF 5-Star na Ranggo', value_zh: 'ASJJF 五星级认证赛事' },
  { key: 'hero_subtitle', section: 'hero', label: 'Hero Subtitle', content_type: 'text', sort_order: 1,
    value_en: "Guam's Premier International", value_ja: 'グアム発 国際', value_ko: '괌 최고의 국제',
    value_tl: 'Pangunahing International ng Guam', value_zh: '关岛顶级国际' },
  { key: 'hero_title_line1', section: 'hero', label: 'Hero Title Line 1', content_type: 'text', sort_order: 2,
    value_en: 'Brazilian Jiu-Jitsu', value_ja: 'ブラジリアン柔術', value_ko: '브라질리안 주짓수',
    value_tl: 'Brazilian Jiu-Jitsu', value_zh: '巴西柔术' },
  { key: 'hero_title_line2', section: 'hero', label: 'Hero Title Line 2', content_type: 'text', sort_order: 3,
    value_en: 'Championship', value_ja: '選手権', value_ko: '챔피언십',
    value_tl: 'Championship', value_zh: '锦标赛' },

  # Stats section
  { key: 'stat_competitors', section: 'stats', label: 'Competitor Count', content_type: 'text', sort_order: 0,
    value_en: '1,300+', value_ja: '1,300+', value_ko: '1,300+', value_tl: '1,300+', value_zh: '1,300+' },
  { key: 'stat_competitors_label', section: 'stats', label: 'Competitor Label', content_type: 'text', sort_order: 1,
    value_en: 'Competitors', value_ja: '選手数', value_ko: '선수', value_tl: 'Kalahok', value_zh: '参赛选手' },
  { key: 'stat_countries', section: 'stats', label: 'Country Count', content_type: 'text', sort_order: 2,
    value_en: '6', value_ja: '6', value_ko: '6', value_tl: '6', value_zh: '6' },
  { key: 'stat_countries_label', section: 'stats', label: 'Country Label', content_type: 'text', sort_order: 3,
    value_en: 'Countries', value_ja: '参加国', value_ko: '참가국', value_tl: 'Bansa', value_zh: '参赛国家' },
  { key: 'stat_prize_pool', section: 'stats', label: 'Prize Pool Amount', content_type: 'text', sort_order: 4,
    value_en: '$50K', value_ja: '$50K', value_ko: '$50K', value_tl: '$50K', value_zh: '$50K' },
  { key: 'stat_prize_pool_label', section: 'stats', label: 'Prize Pool Label', content_type: 'text', sort_order: 5,
    value_en: 'Prize Pool', value_ja: '賞金総額', value_ko: '상금', value_tl: 'Prize Pool', value_zh: '奖金池' },
  { key: 'stat_established', section: 'stats', label: 'Established Year', content_type: 'text', sort_order: 6,
    value_en: '2007', value_ja: '2007', value_ko: '2007', value_tl: '2007', value_zh: '2007' },
  { key: 'stat_established_label', section: 'stats', label: 'Established Label', content_type: 'text', sort_order: 7,
    value_en: 'Established', value_ja: '設立年', value_ko: '설립', value_tl: 'Itinatag', value_zh: '创立' },

  # Featured section on homepage
  { key: 'featured_badge', section: 'featured', label: 'Featured Badge', content_type: 'text', sort_order: 0,
    value_en: 'Since 2007', value_ja: '2007年創設', value_ko: '2007년 설립',
    value_tl: 'Simula 2007', value_zh: '创立于2007' },
  { key: 'featured_title', section: 'featured', label: 'Featured Title', content_type: 'text', sort_order: 1,
    value_en: 'The Largest BJJ Tournament in the Marianas', value_ja: 'マリアナ諸島最大の柔術トーナメント',
    value_ko: '마리아나 제도 최대의 주짓수 대회', value_tl: 'Ang Pinakamalaking BJJ Tournament sa Marianas',
    value_zh: '马里亚纳群岛最大的柔术锦标赛' },
  { key: 'featured_desc', section: 'featured', label: 'Featured Description', content_type: 'text', sort_order: 2,
    value_en: "What started as a local Guam tournament in 2007 has grown into an international phenomenon spanning 6 countries with over 1,300 competitors and $2M in economic impact.",
    value_ja: '2007年にグアムのローカル大会として始まり、今や6カ国1,300人以上の選手が参加し、経済効果2億円以上の国際的イベントに成長しました。',
    value_ko: '2007년 괌의 로컬 대회로 시작하여, 현재 6개국 1,300명 이상의 선수가 참가하고 경제 효과 200만 달러 이상의 국제 이벤트로 성장했습니다.',
    value_tl: 'Nagsimula bilang isang lokal na torneo sa Guam noong 2007, lumago na ito sa isang internasyonal na pangyayari na sumasaklaw sa 6 na bansa na may mahigit 1,300 kalahok at $2M na economic impact.',
    value_zh: '2007年从关岛的一场本地比赛起步，如今已发展成为横跨6个国家、拥有1,300多名选手参赛、经济效益超200万美元的国际赛事。' },
  { key: 'economic_impact_value', section: 'featured', label: 'Economic Impact Value', content_type: 'text', sort_order: 3,
    value_en: '$2M', value_ja: '2億円', value_ko: '$2M', value_tl: '$2M', value_zh: '$2M' },
  { key: 'economic_impact_label', section: 'featured', label: 'Economic Impact Label', content_type: 'text', sort_order: 4,
    value_en: 'Economic Impact', value_ja: '経済効果', value_ko: '경제 효과',
    value_tl: 'Economic Impact', value_zh: '经济效益' },
  { key: 'spectators_value', section: 'featured', label: 'Spectators Value', content_type: 'text', sort_order: 5,
    value_en: '5K+', value_ja: '5,000+', value_ko: '5,000+', value_tl: '5K+', value_zh: '5,000+' },
  { key: 'spectators_label', section: 'featured', label: 'Spectators Label', content_type: 'text', sort_order: 6,
    value_en: 'Spectators', value_ja: '観客数', value_ko: '관중', value_tl: 'Manonood', value_zh: '观众' },
  { key: 'international_reach_title', section: 'featured', label: 'International Reach Title', content_type: 'text', sort_order: 7,
    value_en: 'International Reach', value_ja: '国際展開', value_ko: '국제 네트워크',
    value_tl: 'Pandaigdigang Abot', value_zh: '国际影响力' },
  { key: 'international_reach_desc', section: 'featured', label: 'International Reach Description', content_type: 'text', sort_order: 8,
    value_en: "Partners in Korea, Japan, Taiwan, Philippines, and Hong Kong. Featured in 30,000+ printed magazines across Asia.",
    value_ja: '韓国、日本、台湾、フィリピン、香港にパートナー。アジア全域で30,000部以上の雑誌に掲載。',
    value_ko: '한국, 일본, 대만, 필리핀, 홍콩에 파트너. 아시아 전역 30,000부 이상의 잡지에 게재.',
    value_tl: 'Mga partner sa Korea, Japan, Taiwan, Pilipinas, at Hong Kong. Nai-feature sa 30,000+ naka-print na magazine sa buong Asia.',
    value_zh: '在韩国、日本、台湾、菲律宾和香港拥有合作伙伴。在亚洲各地30,000多份印刷杂志上刊登。' },

  # About page
  { key: 'about_hero_title', section: 'about', label: 'About Hero Title', content_type: 'text', sort_order: 0,
    value_en: 'About the Marianas Open', value_ja: 'マリアナスオープンについて', value_ko: '마리아나스 오픈 소개',
    value_tl: 'Tungkol sa Marianas Open', value_zh: '关于马里亚纳斯公开赛' },
  { key: 'about_hero_subtitle', section: 'about', label: 'About Hero Subtitle', content_type: 'text', sort_order: 1,
    value_en: "Guam's premier martial arts tournament since 2007", value_ja: '2007年から続くグアムのプレミア格闘技大会',
    value_ko: '2007년부터 이어져 온 괌의 프리미어 무술 대회', value_tl: 'Ang premier na torneo ng martial arts ng Guam mula 2007',
    value_zh: '自2007年以来关岛首屈一指的武术赛事' },
  { key: 'about_story_title', section: 'about', label: 'Story Section Title', content_type: 'text', sort_order: 2,
    value_en: 'Our Story', value_ja: '私たちの物語', value_ko: '우리의 이야기',
    value_tl: 'Ang Aming Kwento', value_zh: '我们的故事' },
  { key: 'about_p1', section: 'about', label: 'About Paragraph 1', content_type: 'text', sort_order: 3,
    value_en: "Since its inception in 2007, the Marianas Open has grown into one of the premier martial arts tournaments in the Pacific region. Hosted annually in Guam, this event has emerged as a symbol of excellence, uniting athletes, families, and supporters from around the world.",
    value_ja: '2007年の創設以来、マリアナスオープンは太平洋地域で最も権威ある格闘技大会のひとつに成長しました。グアムで毎年開催されるこのイベントは、世界中のアスリート、家族、サポーターを結びつける卓越の象徴となっています。',
    value_ko: '2007년 창설 이래 마리아나스 오픈은 태평양 지역 최고의 무술 대회로 성장했습니다. 괌에서 매년 개최되며 전 세계 선수, 가족, 서포터를 하나로 모으는 탁월함의 상징이 되었습니다.',
    value_tl: 'Mula nang maitatag noong 2007, ang Marianas Open ay naging isa sa mga nangungunang torneo ng martial arts sa rehiyon ng Pasipiko. Ginaganap taun-taon sa Guam, ang kaganapang ito ay naging simbolo ng kahusayan, nagbubuklod ng mga atleta, pamilya, at tagasuporta mula sa buong mundo.',
    value_zh: '自2007年创办以来，马里亚纳斯公开赛已成长为太平洋地区最著名的武术赛事之一。每年在关岛举办，这项赛事已成为卓越的象征，将世界各地的运动员、家庭和支持者团结在一起。' },
  { key: 'about_p2', section: 'about', label: 'About Paragraph 2', content_type: 'text', sort_order: 4,
    value_en: "The Marianas Open is more than just a competition—it's a celebration of community, culture, and the spirit of martial arts. Over the years, it has expanded into an international series, with tournaments held in Japan, the Philippines, Korea, and Guam, culminating in the grand finale on our home island.",
    value_ja: 'マリアナスオープンは単なる競技会ではありません—コミュニティ、文化、そして格闘技の精神を祝う祭典です。長年にわたり、日本、フィリピン、韓国、グアムで大会を開催する国際シリーズに拡大し、ホームアイランドでのグランドフィナーレで幕を閉じます。',
    value_ko: '마리아나스 오픈은 단순한 대회가 아닌 커뮤니티, 문화, 무술의 정신을 기념하는 축제입니다. 일본, 필리핀, 한국, 괌에서 개최되는 국제 시리즈로 확장되었습니다.',
    value_tl: 'Ang Marianas Open ay higit pa sa isang kompetisyon—ito ay isang pagdiriwang ng komunidad, kultura, at espiritu ng martial arts. Sa mga nakaraang taon, lumawak ito sa isang internasyonal na serye, na may mga torneo sa Japan, Pilipinas, Korea, at Guam.',
    value_zh: '马里亚纳斯公开赛不仅仅是一场比赛——它是社区、文化和武术精神的庆典。多年来，它已扩展为国际系列赛，在日本、菲律宾、韩国和关岛举办比赛。' },
  { key: 'about_p3', section: 'about', label: 'About Paragraph 3', content_type: 'text', sort_order: 5,
    value_en: "Every year, the Marianas Open attracts participants of all ages and skill levels, from novice competitors to seasoned champions. Our commitment to excellence is reflected in the quality of competition and the sense of camaraderie that defines the event.",
    value_ja: '毎年、マリアナスオープンは初心者からチャンピオンまで、あらゆる年齢とレベルの参加者を集めています。卓越へのコミットメントは、競技の質とイベントを定義する仲間意識に反映されています。',
    value_ko: '매년 초보자부터 챔피언까지 모든 연령과 수준의 참가자를 모읍니다.',
    value_tl: 'Bawat taon, ang Marianas Open ay nag-aanyaya ng mga kalahok sa lahat ng edad at antas ng kasanayan, mula sa mga baguhan hanggang sa mga champion.',
    value_zh: '每年，马里亚纳斯公开赛吸引从新手到冠军的各年龄、各水平的参赛者。' },
  { key: 'about_p4', section: 'about', label: 'About Paragraph 4', content_type: 'text', sort_order: 6,
    value_en: "This event will be covered by international media and live-streamed by KUAM News, allowing people from around the world to tune in.",
    value_ja: 'このイベントは国際メディアによる取材とKUAMニュースによるライブ配信が行われ、世界中から視聴できます。',
    value_ko: '국제 미디어 취재와 KUAM 뉴스 라이브 스트리밍으로 전 세계에서 시청할 수 있습니다.',
    value_tl: 'Ang kaganapan ay sasakupin ng internasyonal na media at i-live-stream ng KUAM News, na nagpapahintulot sa mga tao sa buong mundo na manood.',
    value_zh: '赛事将由国际媒体报道并由KUAM新闻进行直播，让全球观众观看。' },
  { key: 'about_p5', section: 'about', label: 'About Paragraph 5', content_type: 'text', sort_order: 7,
    value_en: "Join us as we continue to build on this legacy, making each year's Marianas Open better than the last. Together, we can support the next generation of martial artists and strengthen the bonds that unite us.",
    value_ja: 'このレガシーを築き続け、毎年のマリアナスオープンをより良いものにしていきましょう。次世代の格闘家を支援し、絆を強めましょう。',
    value_ko: '이 유산을 이어가며 차세대 무술인을 지원합시다.',
    value_tl: 'Samahan kami habang patuloy naming binubuo ang legacy na ito. Sama-sama, masusuportahan natin ang susunod na henerasyon ng mga martial artist.',
    value_zh: '加入我们，继续建设这一传统。让我们一起支持下一代武术家。' },
]

contents.each do |attrs|
  SiteContent.find_or_create_by!(key: attrs[:key]) do |c|
    attrs.each { |k, v| c.send("#{k}=", v) unless k == :key }
  end
end

puts "Seeded #{contents.size} site content entries."
